#+title:夸父

#+begin_quote
夸父不量力，欲追日景，逮之于禺谷。捋饮河而不足也，将走大泽，未至，死于此。

《山海经·大荒北经》
#+end_quote

* 屠龙之技
这是一系列的讲义或者笔记，尝试着基于费曼学习法，通过输出倒逼输入的方式来自我学习。此法听闻已久，以为找不到合适的人来教，所以并未使用；随后发现并不一定是要去教授他人，自己写讲义可以达到同样的效果。

笔记就是将所学知识精简和提炼的过程，抓住要点、重点，以便日后复习时能够快速回忆，建立联系；或者是在需要查找资料是方便索引。

而讲义则需要尝试将所学知识编写成一部新的教材，将经过自己头脑思考和加工后的内容，使用自己的语言重新组织，最后输出到文字或者多媒体上。

简而言之，相对于原始知识，笔记内容应该更少，讲义内容不会更少。

我愿称之为屠龙之技，不能说华而不实，只能说异于常人。

追求真理，就像西西弗斯推石上山，永无止境，每一步都比前一步更难十倍。西西弗斯是被罚于此，是对现实的妥协与和解，即使能够认识到“西西弗斯的幸福”，也不过是一种自我安慰。

如夸父逐日，虽不量力，但义无反顾，且至死不渝。

共勉。

* 目录
- 元认知主要讲述一些获取知识之前的知识，比如如何阅读、如何规划时间、如何保持心态等
- 数学尝试从数理逻辑开始，按演绎的视角去构建只是体现
- 哲学尝试按照严格的逻辑形式，对各种观念给出自己理解后的解读

* 建构
本项目是由 [[https://typst.app/][Typst]] 写成。 Typst 泰裤辣！

安装 Typst 之后运行 ~build.sh~ ，里面只是一些编译操作。每个子目录是一个项目，项目的入口文件是 ~build.typ~.

+=Release 大概每个月发布一次吧。+ 不会弄 Action 发版，有机会再研究。

* Todo
** 元认知
- [X] 睡眠
- [-] 身体
  - [ ] 健身
  - [X] 轻瑜伽
- [ ] 沟通
- [ ] 发声
- [ ] 习惯
- [ ] 饮食
- [ ] 记忆
- [ ] 语言
- [ ] 计划
- [ ] 资源
  - 书籍： annas archive, ligensis
  - 视频：b 站，youtube
- [ ] 笔记：费曼学习法
  - 先复制
  - 用自己的话重新加工
  - 找到和其他知识点的联系
  - 找到适当的例子
- [ ] 番茄闹钟

** 逻辑
** 数学
** 微积分 -> 数学分析
** 线性代数 -> 高等代数
** 哲学
