name: Compile typst to pdf
on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - uses: typst-community/setup-typst@v3

      - name: Setup fonts
        run: |
          mkdir fonts
          wget https://github.com/lxgw/LxgwWenKai/releases/download/v1.320/lxgw-wenkai-v1.320.zip
          unzip lxgw-wenkai-v1.320.zip
          cp -r lxgw-wenkai-v1.320/* fonts
          wget https://github.com/adobe-fonts/source-han-serif/releases/download/2.002R/09_SourceHanSerifSC.zip
          unzip 09_SourceHanSerifSC.zip
          cp -r OTF/SimplifiedChinese/* fonts

      - uses: actions/checkout@v4
      - run: mkdir Kuafu
      - run: TYPST_FONT_PATHS="$(pwd)/fonts" ./build.sh

      - run: |
          pwd
          ls

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'Kuafu.zip'
          path: Kuafu


      - run: ls
      - run: mv Kuafu.zip Kuafu/
      - run: ls Kuafu

      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "Kuafu/*"
          token: ${{ secrets.GITHUB_TOKEN }}
