name: Compile typst to pdf
on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set Timezone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: Setup Typst
        uses: typst-community/setup-typst@v3

      - name: Setup Font
        uses: fontist/setup-fontist@v2
      - run: fontist create-formula https://github.com/lxgw/LxgwWenKai/releases/download/v1.320/lxgw-wenkai-v1.320.zip
      - run: fontist create-formula https://github.com/adobe-fonts/source-han-serif/releases/download/2.002R/09_SourceHanSerifSC.zip
      - run: fontist list "source"
      - run: fontist list "lxgw"
      
      # - name: Compile Files
        # run: typst compile paper.typ paper.pdf
