name: Compile typst to pdf
on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - uses: typst-community/setup-typst@v3

      - name: Setup fonts
        run: |
          mkdir fonts
          wget https://github.com/lxgw/LxgwWenKai/releases/download/v1.320/lxgw-wenkai-v1.320.zip
          unzip lxgw-wenkai-v1.320.zip
          cp -r lxgw-wenkai-v1.320/* fonts
          wget https://github.com/adobe-fonts/source-han-serif/releases/download/2.002R/09_SourceHanSerifSC.zip
          unzip 09_SourceHanSerifSC.zip
          cp -r OTF/SimplifiedChinese/* fonts

      - run: ls ${{ github.workspace }}
      - run: ls fonts
      - run: pwd
        
      - uses: actions/checkout@v4
      - run: ./build.sh
